### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by steache** [ubc/satis-go-docker#2]
Hello, We are using your docker image, it's perfect! :) 
There is only one little problem, that we ran into.
After running for few weeks/months there are hundreds/thousands of zombie processes left behind. :/
Didn't you run into this yourself? :)

![2019-03-12_1005](https://user-images.githubusercontent.com/34166829/54187696-7043ca80-44ae-11e9-869f-143685354e74.png)

![2019-03-12_1005_001](https://user-images.githubusercontent.com/34166829/54187701-720d8e00-44ae-11e9-9d5b-b6f524be5237.png)

Restarting the container does help, so it's not a problem, but an unpleasant situation to be in.

**Comment by xcompass** [comment]
I've made some change and updated to the latest version. Briefly tested, it seems fixed the issue. Please give it a try and let me know if there is any problem.
